### ISSUE TITLE
Compatible with AFNetworking?

### ISSUE THREAD

**Issue by ronnyandre** [xmartlabs/XLRemoteImageView#7]
I use AFNetworking in my project, and with XLRemoteImageView i get alot of compiler errors. Is XLRemoteImageView and AFNetworking compatible with eachother?

![skjermbilde 2014-05-12 kl 13 42 09](https://cloud.githubusercontent.com/assets/68879/2943877/7f67be94-d9ca-11e3-93f1-e6ef72ff2a4f.png)

**Comment by rahulvyas** [comment]
now AFNetworking 3.0 comes and it's not working with that.
